# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-case-conflict
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: LICENSE
-   repo: local
    hooks:
    -   id: lint
        name: Lint
        entry: make lint
        types: [python]
        language: system
        pass_filenames: false
