[envs.default.scripts]
all = [
    'hatch run test:cov',
]

[envs.test]
dependencies = [
  'coverage[toml]',
  'pytest',
  'pytest-cov',
]

[envs.test.scripts]
cov = 'pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=deeprl --cov=tests'

[[envs.test.matrix]]
python = ['38', '39', '310']
