env:
  # name: MountainCarContinuous-v0
  # name: HalfCheetah-v4
  # name: Pendulum-v1
  name: InvertedDoublePendulum-v4
  # name: Humanoid-v4
  # name: Ant-v4
  num_episodes: 1_000_000
  device: cuda:1

td3:
  hidden_dims: [256, 256]
  actor_lr : 3e-4
  critic_lr: 3e-4
  memory_capacity: 1e6
  batch_size: 256
  discount_factor: 0.99
  target_smoothing_factor: 5e-3
  smoothing_noise_stdev: 0.2
  smoothing_noise_clip: 0.5
  action_noise_stdev: 0.1
